// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RespType int32

const (
	RespType_NONE    RespType = 0
	RespType_ASCEND  RespType = 1
	RespType_DESCEND RespType = 2
)

var RespType_name = map[int32]string{
	0: "NONE",
	1: "ASCEND",
	2: "DESCEND",
}

var RespType_value = map[string]int32{
	"NONE":    0,
	"ASCEND":  1,
	"DESCEND": 2,
}

func (x RespType) String() string {
	return proto.EnumName(RespType_name, int32(x))
}

func (RespType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

type SayParam struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayParam) Reset()         { *m = SayParam{} }
func (m *SayParam) String() string { return proto.CompactTextString(m) }
func (*SayParam) ProtoMessage()    {}
func (*SayParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *SayParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayParam.Unmarshal(m, b)
}
func (m *SayParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayParam.Marshal(b, m, deterministic)
}
func (m *SayParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayParam.Merge(m, src)
}
func (m *SayParam) XXX_Size() int {
	return xxx_messageInfo_SayParam.Size(m)
}
func (m *SayParam) XXX_DiscardUnknown() {
	xxx_messageInfo_SayParam.DiscardUnknown(m)
}

var xxx_messageInfo_SayParam proto.InternalMessageInfo

func (m *SayParam) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Pair struct {
	Key                  int32    `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Values               string   `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pair) Reset()         { *m = Pair{} }
func (m *Pair) String() string { return proto.CompactTextString(m) }
func (*Pair) ProtoMessage()    {}
func (*Pair) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *Pair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pair.Unmarshal(m, b)
}
func (m *Pair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pair.Marshal(b, m, deterministic)
}
func (m *Pair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pair.Merge(m, src)
}
func (m *Pair) XXX_Size() int {
	return xxx_messageInfo_Pair.Size(m)
}
func (m *Pair) XXX_DiscardUnknown() {
	xxx_messageInfo_Pair.DiscardUnknown(m)
}

var xxx_messageInfo_Pair proto.InternalMessageInfo

func (m *Pair) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *Pair) GetValues() string {
	if m != nil {
		return m.Values
	}
	return ""
}

type SayResponse struct {
	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	// 数组
	Values []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	// map
	Header               map[string]*Pair `protobuf:"bytes,3,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Type                 RespType         `protobuf:"varint,4,opt,name=type,proto3,enum=model.RespType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SayResponse) Reset()         { *m = SayResponse{} }
func (m *SayResponse) String() string { return proto.CompactTextString(m) }
func (*SayResponse) ProtoMessage()    {}
func (*SayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *SayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayResponse.Unmarshal(m, b)
}
func (m *SayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayResponse.Marshal(b, m, deterministic)
}
func (m *SayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayResponse.Merge(m, src)
}
func (m *SayResponse) XXX_Size() int {
	return xxx_messageInfo_SayResponse.Size(m)
}
func (m *SayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SayResponse proto.InternalMessageInfo

func (m *SayResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SayResponse) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *SayResponse) GetHeader() map[string]*Pair {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SayResponse) GetType() RespType {
	if m != nil {
		return m.Type
	}
	return RespType_NONE
}

func init() {
	proto.RegisterEnum("model.RespType", RespType_name, RespType_value)
	proto.RegisterType((*SayParam)(nil), "model.SayParam")
	proto.RegisterType((*Pair)(nil), "model.Pair")
	proto.RegisterType((*SayResponse)(nil), "model.SayResponse")
	proto.RegisterMapType((map[string]*Pair)(nil), "model.SayResponse.HeaderEntry")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x5d, 0x4b, 0xb4, 0x40,
	0x14, 0xc7, 0x77, 0x7c, 0x7b, 0xdc, 0x33, 0x0f, 0xad, 0x9c, 0x8b, 0x90, 0x25, 0xc2, 0xec, 0x46,
	0x82, 0x24, 0x8c, 0x22, 0xba, 0x8b, 0xd6, 0xd8, 0x2b, 0x5b, 0xc6, 0xbe, 0xc0, 0xd4, 0x0e, 0x15,
	0xa9, 0x23, 0x6a, 0xc1, 0x7c, 0xd7, 0x3e, 0x4c, 0x38, 0x1a, 0x6b, 0xec, 0xdd, 0x39, 0xfc, 0x5f,
	0x38, 0xbf, 0x19, 0xf8, 0xff, 0x22, 0xcb, 0x52, 0x56, 0x71, 0xdd, 0xc8, 0x4e, 0xa2, 0x5d, 0xca,
	0xad, 0x28, 0xc2, 0x23, 0x70, 0x73, 0xae, 0x36, 0xbc, 0xe1, 0x25, 0x7a, 0x60, 0x96, 0xed, 0xab,
	0x4f, 0x02, 0x12, 0xcd, 0x59, 0x3f, 0x86, 0x17, 0x60, 0x6d, 0xf8, 0x7b, 0xd3, 0x2b, 0x1f, 0x42,
	0x69, 0xc5, 0x66, 0xfd, 0x88, 0x87, 0xe0, 0x7c, 0xf1, 0xe2, 0x53, 0xb4, 0xbe, 0xa1, 0xed, 0xe3,
	0x16, 0x7e, 0x13, 0xa0, 0x39, 0x57, 0x4c, 0xb4, 0xb5, 0xac, 0x5a, 0xb1, 0xdf, 0xf9, 0x27, 0x69,
	0xee, 0x92, 0x78, 0x0d, 0xce, 0x9b, 0xe0, 0x5b, 0xd1, 0xf8, 0x66, 0x60, 0x46, 0x34, 0x39, 0x8e,
	0xf5, 0x85, 0xf1, 0xa4, 0x2d, 0x5e, 0x6b, 0x43, 0x5a, 0x75, 0x8d, 0x62, 0xa3, 0x1b, 0x4f, 0xc1,
	0xea, 0x54, 0x2d, 0x7c, 0x2b, 0x20, 0xd1, 0x41, 0xb2, 0x18, 0x53, 0x7d, 0xe4, 0x49, 0xd5, 0x82,
	0x69, 0x71, 0xf9, 0x00, 0x74, 0x92, 0x9d, 0xf2, 0xcc, 0x07, 0x9e, 0x13, 0xb0, 0xf5, 0x1d, 0x1a,
	0x87, 0x26, 0x74, 0xac, 0xe9, 0xe9, 0xd9, 0xa0, 0xdc, 0x1a, 0x37, 0xe4, 0xec, 0x1c, 0xdc, 0xdf,
	0x66, 0x74, 0xc1, 0xca, 0x1e, 0xb3, 0xd4, 0x9b, 0x21, 0x80, 0x73, 0x97, 0xdf, 0xa7, 0xd9, 0xca,
	0x23, 0x48, 0xe1, 0xdf, 0x2a, 0x1d, 0x16, 0x23, 0xb9, 0x02, 0x33, 0xe7, 0x0a, 0x63, 0xb0, 0xd7,
	0xa2, 0x28, 0x24, 0x2e, 0x76, 0x4c, 0xfa, 0xc9, 0x97, 0xb8, 0x0f, 0x19, 0xce, 0x9e, 0x1d, 0xfd,
	0x45, 0x97, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8d, 0xdc, 0x99, 0xd9, 0xb2, 0x01, 0x00, 0x00,
}
