// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db.proto

package dbrproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DBUsrDataReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBUsrDataReq) Reset()         { *m = DBUsrDataReq{} }
func (m *DBUsrDataReq) String() string { return proto.CompactTextString(m) }
func (*DBUsrDataReq) ProtoMessage()    {}
func (*DBUsrDataReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{0}
}

func (m *DBUsrDataReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBUsrDataReq.Unmarshal(m, b)
}
func (m *DBUsrDataReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBUsrDataReq.Marshal(b, m, deterministic)
}
func (m *DBUsrDataReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBUsrDataReq.Merge(m, src)
}
func (m *DBUsrDataReq) XXX_Size() int {
	return xxx_messageInfo_DBUsrDataReq.Size(m)
}
func (m *DBUsrDataReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DBUsrDataReq.DiscardUnknown(m)
}

var xxx_messageInfo_DBUsrDataReq proto.InternalMessageInfo

type DBSaveReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBSaveReq) Reset()         { *m = DBSaveReq{} }
func (m *DBSaveReq) String() string { return proto.CompactTextString(m) }
func (*DBSaveReq) ProtoMessage()    {}
func (*DBSaveReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{1}
}

func (m *DBSaveReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBSaveReq.Unmarshal(m, b)
}
func (m *DBSaveReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBSaveReq.Marshal(b, m, deterministic)
}
func (m *DBSaveReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBSaveReq.Merge(m, src)
}
func (m *DBSaveReq) XXX_Size() int {
	return xxx_messageInfo_DBSaveReq.Size(m)
}
func (m *DBSaveReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DBSaveReq.DiscardUnknown(m)
}

var xxx_messageInfo_DBSaveReq proto.InternalMessageInfo

func (m *DBSaveReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DBSaveReq) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type DBSaveRsp struct {
	Errorid              int32    `protobuf:"varint,1,opt,name=errorid,proto3" json:"errorid,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBSaveRsp) Reset()         { *m = DBSaveRsp{} }
func (m *DBSaveRsp) String() string { return proto.CompactTextString(m) }
func (*DBSaveRsp) ProtoMessage()    {}
func (*DBSaveRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{2}
}

func (m *DBSaveRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBSaveRsp.Unmarshal(m, b)
}
func (m *DBSaveRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBSaveRsp.Marshal(b, m, deterministic)
}
func (m *DBSaveRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBSaveRsp.Merge(m, src)
}
func (m *DBSaveRsp) XXX_Size() int {
	return xxx_messageInfo_DBSaveRsp.Size(m)
}
func (m *DBSaveRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DBSaveRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DBSaveRsp proto.InternalMessageInfo

func (m *DBSaveRsp) GetErrorid() int32 {
	if m != nil {
		return m.Errorid
	}
	return 0
}

func (m *DBSaveRsp) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DBSaveRsp) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type DBUsrData struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Userid               int32    `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBUsrData) Reset()         { *m = DBUsrData{} }
func (m *DBUsrData) String() string { return proto.CompactTextString(m) }
func (*DBUsrData) ProtoMessage()    {}
func (*DBUsrData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{3}
}

func (m *DBUsrData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBUsrData.Unmarshal(m, b)
}
func (m *DBUsrData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBUsrData.Marshal(b, m, deterministic)
}
func (m *DBUsrData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBUsrData.Merge(m, src)
}
func (m *DBUsrData) XXX_Size() int {
	return xxx_messageInfo_DBUsrData.Size(m)
}
func (m *DBUsrData) XXX_DiscardUnknown() {
	xxx_messageInfo_DBUsrData.DiscardUnknown(m)
}

var xxx_messageInfo_DBUsrData proto.InternalMessageInfo

func (m *DBUsrData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DBUsrData) GetUserid() int32 {
	if m != nil {
		return m.Userid
	}
	return 0
}

type DBGenuid struct {
	Genuid               int32    `protobuf:"varint,1,opt,name=genuid,proto3" json:"genuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBGenuid) Reset()         { *m = DBGenuid{} }
func (m *DBGenuid) String() string { return proto.CompactTextString(m) }
func (*DBGenuid) ProtoMessage()    {}
func (*DBGenuid) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{4}
}

func (m *DBGenuid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBGenuid.Unmarshal(m, b)
}
func (m *DBGenuid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBGenuid.Marshal(b, m, deterministic)
}
func (m *DBGenuid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBGenuid.Merge(m, src)
}
func (m *DBGenuid) XXX_Size() int {
	return xxx_messageInfo_DBGenuid.Size(m)
}
func (m *DBGenuid) XXX_DiscardUnknown() {
	xxx_messageInfo_DBGenuid.DiscardUnknown(m)
}

var xxx_messageInfo_DBGenuid proto.InternalMessageInfo

func (m *DBGenuid) GetGenuid() int32 {
	if m != nil {
		return m.Genuid
	}
	return 0
}

type DBUsrDataRsp struct {
	Errorid              int32        `protobuf:"varint,1,opt,name=errorid,proto3" json:"errorid,omitempty"`
	Accountid            int32        `protobuf:"varint,2,opt,name=accountid,proto3" json:"accountid,omitempty"`
	Usrdatas             []*DBUsrData `protobuf:"bytes,3,rep,name=usrdatas,proto3" json:"usrdatas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DBUsrDataRsp) Reset()         { *m = DBUsrDataRsp{} }
func (m *DBUsrDataRsp) String() string { return proto.CompactTextString(m) }
func (*DBUsrDataRsp) ProtoMessage()    {}
func (*DBUsrDataRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{5}
}

func (m *DBUsrDataRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBUsrDataRsp.Unmarshal(m, b)
}
func (m *DBUsrDataRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBUsrDataRsp.Marshal(b, m, deterministic)
}
func (m *DBUsrDataRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBUsrDataRsp.Merge(m, src)
}
func (m *DBUsrDataRsp) XXX_Size() int {
	return xxx_messageInfo_DBUsrDataRsp.Size(m)
}
func (m *DBUsrDataRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DBUsrDataRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DBUsrDataRsp proto.InternalMessageInfo

func (m *DBUsrDataRsp) GetErrorid() int32 {
	if m != nil {
		return m.Errorid
	}
	return 0
}

func (m *DBUsrDataRsp) GetAccountid() int32 {
	if m != nil {
		return m.Accountid
	}
	return 0
}

func (m *DBUsrDataRsp) GetUsrdatas() []*DBUsrData {
	if m != nil {
		return m.Usrdatas
	}
	return nil
}

func init() {
	proto.RegisterType((*DBUsrDataReq)(nil), "dbrproto.DBUsrDataReq")
	proto.RegisterType((*DBSaveReq)(nil), "dbrproto.DBSaveReq")
	proto.RegisterType((*DBSaveRsp)(nil), "dbrproto.DBSaveRsp")
	proto.RegisterType((*DBUsrData)(nil), "dbrproto.DBUsrData")
	proto.RegisterType((*DBGenuid)(nil), "dbrproto.DBGenuid")
	proto.RegisterType((*DBUsrDataRsp)(nil), "dbrproto.DBUsrDataRsp")
}

func init() { proto.RegisterFile("db.proto", fileDescriptor_8817812184a13374) }

var fileDescriptor_8817812184a13374 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x35, 0x89, 0xad, 0xc9, 0x54, 0x44, 0x46, 0x29, 0xa1, 0x78, 0x28, 0x7b, 0xea, 0x29, 0x42,
	0x0b, 0x7a, 0x14, 0x42, 0xc0, 0x8b, 0x5e, 0x22, 0xfe, 0x80, 0x4d, 0x76, 0x90, 0xa0, 0xe6, 0x63,
	0x37, 0x89, 0x78, 0xf7, 0x87, 0xcb, 0xae, 0x9b, 0xb4, 0x62, 0xf0, 0x36, 0xef, 0xb1, 0xef, 0x63,
	0x66, 0xc1, 0x17, 0x59, 0x54, 0xcb, 0xaa, 0xad, 0xd0, 0x17, 0x99, 0x34, 0x13, 0x3b, 0x83, 0xd3,
	0x24, 0x7e, 0x56, 0x32, 0xe1, 0x2d, 0x4f, 0xa9, 0x61, 0x3b, 0x08, 0x92, 0xf8, 0x89, 0xf7, 0x94,
	0x52, 0x83, 0xe7, 0xe0, 0xbd, 0xd2, 0x67, 0xe8, 0xac, 0x9d, 0x4d, 0x90, 0xea, 0x11, 0x2f, 0x61,
	0xd6, 0xf3, 0xb7, 0x8e, 0x42, 0xd7, 0x70, 0x3f, 0x80, 0x3d, 0x8e, 0x22, 0x55, 0x63, 0x08, 0x27,
	0x24, 0x65, 0x25, 0x0b, 0x61, 0x84, 0xb3, 0x74, 0x80, 0x83, 0x9d, 0x3b, 0x61, 0xe7, 0x1d, 0xda,
	0xdd, 0x6a, 0x3b, 0xdb, 0x09, 0x11, 0x8e, 0x4b, 0xfe, 0x4e, 0xb6, 0x84, 0x99, 0x71, 0x09, 0xf3,
	0x4e, 0x91, 0x4e, 0x70, 0x4d, 0x82, 0x45, 0x8c, 0x81, 0x9f, 0xc4, 0xf7, 0x54, 0x76, 0x85, 0xd0,
	0x6f, 0x5e, 0xcc, 0x64, 0x5b, 0x58, 0xc4, 0x3e, 0x0e, 0x17, 0xfe, 0xb7, 0xee, 0x15, 0x04, 0x3c,
	0xcf, 0xab, 0xae, 0x6c, 0xc7, 0xa0, 0x3d, 0x81, 0xd7, 0xe0, 0x77, 0x4a, 0x0a, 0xde, 0x72, 0x15,
	0x7a, 0x6b, 0x6f, 0xb3, 0xd8, 0x5e, 0x44, 0xc3, 0x55, 0xa3, 0x7d, 0xc2, 0xf8, 0x68, 0xfb, 0xe5,
	0x98, 0x2b, 0x91, 0xec, 0x8b, 0x9c, 0xf0, 0x0e, 0x16, 0x0f, 0x15, 0x17, 0xc3, 0x96, 0xcb, 0x29,
	0x2d, 0x35, 0xab, 0x49, 0x5e, 0xd5, 0xec, 0x08, 0x6f, 0xc0, 0xd7, 0x17, 0x37, 0xea, 0x5f, 0xc9,
	0xf6, 0xf3, 0x56, 0x7f, 0x49, 0xad, 0xcb, 0xe6, 0x86, 0xda, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff,
	0xb0, 0x00, 0xdc, 0xb6, 0x0d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DBServiceClient is the client API for DBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DBServiceClient interface {
	LoadUsrData(ctx context.Context, in *DBUsrDataReq, opts ...grpc.CallOption) (*DBUsrDataRsp, error)
	SaveData(ctx context.Context, in *DBSaveReq, opts ...grpc.CallOption) (*DBSaveRsp, error)
}

type dBServiceClient struct {
	cc *grpc.ClientConn
}

func NewDBServiceClient(cc *grpc.ClientConn) DBServiceClient {
	return &dBServiceClient{cc}
}

func (c *dBServiceClient) LoadUsrData(ctx context.Context, in *DBUsrDataReq, opts ...grpc.CallOption) (*DBUsrDataRsp, error) {
	out := new(DBUsrDataRsp)
	err := c.cc.Invoke(ctx, "/dbrproto.DBService/LoadUsrData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBServiceClient) SaveData(ctx context.Context, in *DBSaveReq, opts ...grpc.CallOption) (*DBSaveRsp, error) {
	out := new(DBSaveRsp)
	err := c.cc.Invoke(ctx, "/dbrproto.DBService/SaveData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DBServiceServer is the server API for DBService service.
type DBServiceServer interface {
	LoadUsrData(context.Context, *DBUsrDataReq) (*DBUsrDataRsp, error)
	SaveData(context.Context, *DBSaveReq) (*DBSaveRsp, error)
}

// UnimplementedDBServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDBServiceServer struct {
}

func (*UnimplementedDBServiceServer) LoadUsrData(ctx context.Context, req *DBUsrDataReq) (*DBUsrDataRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadUsrData not implemented")
}
func (*UnimplementedDBServiceServer) SaveData(ctx context.Context, req *DBSaveReq) (*DBSaveRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveData not implemented")
}

func RegisterDBServiceServer(s *grpc.Server, srv DBServiceServer) {
	s.RegisterService(&_DBService_serviceDesc, srv)
}

func _DBService_LoadUsrData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DBUsrDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServiceServer).LoadUsrData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbrproto.DBService/LoadUsrData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServiceServer).LoadUsrData(ctx, req.(*DBUsrDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBService_SaveData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DBSaveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServiceServer).SaveData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbrproto.DBService/SaveData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServiceServer).SaveData(ctx, req.(*DBSaveReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _DBService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dbrproto.DBService",
	HandlerType: (*DBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadUsrData",
			Handler:    _DBService_LoadUsrData_Handler,
		},
		{
			MethodName: "SaveData",
			Handler:    _DBService_SaveData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "db.proto",
}
